### ISSUE TITLE
Friends on PS5 doesnt show up

### ISSUE THREAD

**Issue by iAroc** [kuebelchris/COTDLiveQualifying#16]
Heyya

i'm playing on pc, and i have a few friends added on pc and ps5. but in the ingame overlay, only the pc friends show up.

Anything i could do to fix this?

**Comment by kuebelchris** [comment]
Hey, there is probably nothing you can do. 
The plugin gets the friendlist from the game API and apparently PS friends are not included in there. 
I'll try to see if there are some other ways to get those friends, although I can't promise anything.

**Comment by iAroc** [comment]
Would be nice. i would also be fine if i can add friends/players manually for the cotd, if that works?

**Comment by kuebelchris** [comment]
I might look into the possibility to maintain a manual list of players. That might be something for future versions

**Comment by iAroc** [comment]
kk

btw i downloaded your project and removed the club stuff since that was broken in the current update. 
for the ps5 players - i saw they are actually loaded in the friends list, but their online status is wrong.

just removing the offline check shows them fine. it wont show players that have no time on the cotd anyway, so that works fine

**Comment by kuebelchris** [comment]
A fixed version for the current update is already in review at openplanet

What status is shown for PS players? Just offline or something else? Could be an option to make it configurable in the plugin which statuses should be tracked

**Comment by iAroc** [comment]
just offline, yes

im my point of view, i would say displaying all users that have a time, and now only those that are online (at least for friends list?) would be neat. else it will also not show if a friend restarts etc.

**Comment by kuebelchris** [comment]
The friendlist is already refreshed every minute, that shouldn't be a problem. Only users with a time are displayed anyways, so that should be fine.

I added the option to display offline friends. It's deactivated by default but can be changed in the settings.

Thanks for the suggestion! :)

**Comment by iAroc** [comment]
played the cup today with your version on git here. had no bugs, nothing.
also my friends on ps5 showed up after i enabled the setting, so that works fine too.

Thanks for it ;)
